services:
  backend:
    image: akshatdikshit/ipl-backend:latest
    ports:
      - "8000:8000"
    # We only map uploads/outputs so your files are saved locally
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    restart: always

  frontend:
    image: akshatdikshit/ipl-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always
