version: '3.8'

services:
  backend:
    image: akshatdikshit/ipl-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./templates:/app/templates
    restart: always

  frontend:
    image: akshatdikshit/ipl-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always
